---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге выводится название, рейтинг, цена со скидкой и без нее

non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Магазин - это SPA-приложение, которое не перезагружает страницу

implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность регистрации и входа
  - Пользователь должен иметь возможность оформить заказ и оплатить его